### PR TITLE
Updated iPad Pro images to 3rd Gen

### PR DESCRIPTION
**Pull request by mikelrob**

### CODE REVIEW

**Comment by mikelrob** [comment]
I signed it!

**Comment by janpio** [comment]
Where do these images comes from @mikelrob? What is their license?

**Comment by mikelrob** [comment]
Images were downloaded from Apple's Market Resources Site
https://developer.apple.com/app-store/marketing/guidelines/#section-products

License Info can be found at https://www.apple.com/legal/intellectual-property/guidelinesfor3rdparties.html

**Comment by getaaron** [comment]
Hmm, that license says *Note: You must obtain express written permission from Apple before using any photograph owned or licensed by Apple*. But the developer site says *Use Apple-provided product images in all your marketing materials to display your app on the Apple devices it supports*, so that seems like express written permission to me.

**Review by janpio — CHANGES_REQUESTED** [review]
The usual iPad Pro images are still needed unfortunately to frame actual iPad Pro 12.9 1st and 2nd gen screenshots. We can't just overwrite those :/

**Comment by mikelrob** [comment]
> The usual iPad Pro images are still needed unfortunately to frame actual iPad Pro 12.9 1st and 2nd gen screenshots. We can't just overwrite those :/

It would be preferable to have all the devices available for automated screenshotting and framing, however I don't think the `frameit` tool in `fastlane` is compatible with this preference currently.
Following on from @getaaron's fine research - 
> Use Apple-provided product images in all your marketing materials to display your app on the Apple devices it supports.

The developer site recommends: `Always use the latest-generation product images for which your app is currently developed.`
See [here](https://developer.apple.com/app-store/marketing/guidelines/)
The latest-generation and only available iPad Pro from Apple is the rounded Liquid Retina screen with notch as depicted in the updated image. I believe the `frameit` would be at it's most useful using these updated images in the PR to attempt to comply with Apple's guidelines.

**Comment by mikelrob** [comment]
> It would be preferable to have all the devices available for automated screenshotting and framing, however I don't think the `frameit` tool in `fastlane` is compatible with this preference currently.

Apologies, I have been working with fastlane version 2.117.0. I have only recently seen the PRs
https://github.com/fastlane/fastlane/pull/14576
https://github.com/fastlane/fastlane/pull/14653

**Comment by janpio** [comment]
No worries, it's a confusing mess what Apple created here by having the same resolution for two devices. We are trying hard to find workarounds, but it takes some time to get all the pieces to the correct place.

**Comment by RSickenberg** [comment]
Any update on this? :-)

**Review by janpio — CHANGES_REQUESTED** [review]
Frames unfortunately can't be added to this repo manually, as this repo is filled via a process: https://github.com/fastlane/fastlane/tree/master/frameit/frames_generator

**Comment by janpio** [comment]
@mikelrob What were the manual steps you took after downloading the images from Apple's site? Maybe we can incorporate these as an additional step to the Facebook Design frame into our frames generator.

**Comment by mikelrob** [comment]
> @mikelrob What were the manual steps you took after downloading the images from Apple's site? Maybe we can incorporate these as an additional step to the Facebook Design frame into our frames generator.

First I had to remove the colour fill within the screen area by reducing it's alpha to zero.
Then I had to resize the images manually as the the 'holes' left in the screen area were a 10 or 12 pixels too large leaving a transparent border between the bezel and the framed screen shot.
Apple only provide one image and it's named Silver, some modification is need to make it look Space Grey.

**Comment by janpio** [comment]
Meh, that doesn't sound too good for automation on our side. Maybe the licence allows you to re-host the files on a repository of yours so we can use _that_ one where you already did this work?

**Comment by mikelrob** [comment]
I'd refer back to @getaaron's fine investigative work again where he highlighted:
>  Use Apple-provided product images in all your marketing materials to display your app on the Apple devices it supports, so that seems like express written permission to me.

Reads to me like Apple allow developers to use their supplied image. I don't see any specific exclusions about hosting the image.

**Comment by mikelrob** [comment]
@janpio I have reinstated the original iPad Pro assets and added the new assets named with the disambiguation file name added to `fastlane` via PR https://github.com/fastlane/fastlane/pull/14576
I've also made a change to `fastlane` `frameit` to allow it to correctly identify the device type from the filename of the image it is attempting to frame, see https://github.com/fastlane/fastlane/pull/14787

**Comment by jordanpichler** [comment]
Any updates on this? 😁

**Comment by jordanpichler** [comment]
Any updates on this? 😁

**Comment by mikelrob** [comment]
No :(

**Comment by getaaron** [comment]
I think the only change still needed is to make the script at https://github.com/fastlane/fastlane/blob/master/frameit/frames_generator/Rakefile download the new assets from somewhere?

**Comment by janpio** [comment]
Download and create the offset json data automatically, yes.

**Comment by RSickenberg** [comment]
Any updates? :)

**Comment by ainame** [comment]
https://github.com/fastlane/fastlane/issues/14713#issuecomment-555994226

**Comment by JulesMoorhouse** [comment]
@janpio can the images @ainame be used?

This also seems useful, buts didn't work for me...
https://github.com/fastlane/frameit-frames/issues/7

**Comment by joshdholtz** [comment]
My apologies on not seeing this PR 😱  Going to close this since out of date but I’m keep a better on on things here now and will get future PRs merged faster 💪

**Pull request closed without merging**
