### PR TITLE
[hotfix] add missing frames for iPad Pro 12.9-inch (2nd generation)

### LINKED ISSUE #18: Frames for iPad Pro 12.9-inch (2nd generation) missing
Since the last version (`1607001240`), the iPad Pro frames are not present anymore, even though App Store Connect still requires screenshots for the iPad Pro 12.9-inch (2nd generation) to be uploaded.

Error logs:
```
Unfortunately device type 'Apple iPad Pro' is not available in Silver, falling back to Space Gray...
Couldn't find template for screenshot type 'Apple iPad Pro Space Gray'
Please run `fastlane frameit download_frames` to download the latest frames
```

### PR DESCRIPTION
**Pull request by jhandguy**
The frames for the iPad Pro 12.9-inch (2nd generation) seem to have been removed in the previous version (1607001240) although still present in the `offsets.json` file.

This PR brings those back as App Store Connect still requires screenshots from the iPad Pro 12.9-inch (2nd generation) to be uploaded.

Fixes https://github.com/fastlane/frameit-frames/issues/18

### CODE REVIEW

**Comment by jhandguy** [comment]
Hi @joshdholtz, anything I can do to help move this PR forward?
Do you maybe need some clarification on the issue?

**Comment by joshdholtz** [comment]
@jhandguy Oops sorry! Looking now 😊

**Review by joshdholtz — APPROVED** [review]
Looks good to me!! Thank you ❤️

**Comment by joshdholtz** [comment]
@jhandguy Question! How did you make this PR? 😇 You didn’t do this by running the `Rakefile`, did you? Did you manually place these frames back in here? 😬

**Comment by edwinveger** [comment]
FYI Changes in this PR appear to have been overridden in [a subsequent commit](e884a3e95c64a2c2a4bef895ee4a6a3d974aa42a). 
The App Store requires iPad Pro 2nd gen screenshots and I had to supply `"device_frame_version": "1607001240"` in my Framefile.json to get frameit to recognize my images.

**Pull request merged**
