### PR TITLE
[FrameIt] added new devices

### PR DESCRIPTION
**Pull request by sathoeni**
- iPhone 13

### CODE REVIEW

**Comment by sathoeni** [comment]
@joshdholtz Could you merge this pull request?

**Comment by JorgeFrias** [comment]
> @joshdholtz

Please... :)

**Comment by adarhef** [comment]
@joshdholtz Pretty please :3

**Comment by JosephDuffy** [comment]
It looks like there's no way to point frameit at a fork. @joshdholtz is there an ETA on this getting merged?

**Comment by dweekly** [comment]
Ping - please merge?

**Comment by Brma1048** [comment]
Any updates on this? We need this...Please merge. @joshdholtz

**Comment by joshdholtz** [comment]
I have no idea why I don't get notifications from this repo 😱 I'm so sorry, fam! 

Please yell at me on Twitter if this happens again (I hope it won't 🤷‍♂️)

**Review by joshdholtz — APPROVED** [review]
Seems good to me! Thank you so much for making this PR and sorry I didn't see it 😔

**Comment by Brma1048** [comment]
@sathoeni I think [fastlane/framit](https://github.com/fastlane/fastlane/blob/master/frameit/lib/frameit/device_types.rb) must also be updated because in this file there didn't exist these new devices like the samsung galaxy S21 Ultra that you have added as frames. For example if I say **force_device_type: "Samsung Galaxy S21 Ultra"** it gives me this error msg:
`"Invalid device type 'Samsung Galaxy S21 Ultra'. Available values: iPhone XS, iPhone XR, iPhone XS Max, iPhone 11, iPhone 11 Pro, iPhone 11 Pro Max, iPhone 12, iPhone 12 Pro, iPhone 12 Pro Max, iPhone 12 Mini, iPad 10.2, iPad Air 2, iPad Air (2019), iPad Mini 4, iPad Mini (2019), iPad Pro, iPad Pro (12.9-inch) (3rd generation), iPad Pro (12.9-inch) (4th generation), iPad Pro (10.5-inch), iPad Pro (11-inch), MacBook, Google Pixel 3, Google Pixel 3 XL, Google Pixel 4, Google Pixel 4 XL, HTC One A9, HTC One M8, Huawei P8, Motorola Moto E, Motorola Moto G, Nexus 4, Nexus 5X, Nexus 6P, Nexus 9, Samsung Galaxy Grand Prime, Samsung Galaxy Note 5, Samsung Galaxy Note 10, Samsung Galaxy Note 10+, Samsung Galaxy S Duos, Samsung Galaxy S3, Samsung Galaxy S5, Samsung Galaxy S7, Samsung Galaxy S8, Samsung Galaxy S9, Samsung Galaxy S10, Samsung Galaxy S10+, Xiaomi Mi Mix Alpha, iPhone 5s, iPhone 5c, iPhone SE, iPhone 6s, iPhone 6s Plus, iPhone 7, iPhone 7 Plus, iPhone 8, iPhone 8 Plus, iPhone X"`
Or is there another way to use these new device frames? 
Did it worked for you @JosephDuffy

**Comment by joshdholtz** [comment]
I’ll try and get a new fastlane version out with these fixes in a few days. I have to travel today for a funeral this weekend so I probably won’t be able to get it done until next week ☹️

**Comment by Brma1048** [comment]
@joshdholtz perfect, thanks a lot 👍🏼

**Pull request merged**
